#!/bin/bash -e

THIS_STAGE="$(pwd -P)"
if [ -f "$THIS_STAGE/files/build-polish.env" ]; then
  # Generated by the image builder; values are shell-escaped and contain no secrets.
  # shellcheck disable=SC1091
  source "$THIS_STAGE/files/build-polish.env"
fi

YWD_OS_VERSION="${YWD_OS_VERSION:-M4.1-polish-dev}"
YWD_SOURCE_BRANCH="${YWD_SOURCE_BRANCH:-dev-os}"
YWD_SOURCE_COMMIT="${YWD_SOURCE_COMMIT:-unknown}"
YWD_PI_GEN_COMMIT="${YWD_PI_GEN_COMMIT:-unknown}"

install -d -m 0755 \
  "${ROOTFS_DIR}/usr/local/libexec" \
  "${ROOTFS_DIR}/usr/local/bin" \
  "${ROOTFS_DIR}/etc/profile.d" \
  "${ROOTFS_DIR}/etc/ywd-hotspot"

install -m 0755 files/ywd-system-info.py "${ROOTFS_DIR}/usr/local/libexec/ywd-system-info"
install -m 0755 files/ywd-info-wrapper.sh "${ROOTFS_DIR}/usr/local/bin/ywd-info"
ln -sfn ywd-info "${ROOTFS_DIR}/usr/local/bin/ywd-services"
ln -sfn ywd-info "${ROOTFS_DIR}/usr/local/bin/ywd-build"
install -m 0755 files/ywd-logs.sh "${ROOTFS_DIR}/usr/local/bin/ywd-logs"

install -m 0644 files/ywd-env.sh "${ROOTFS_DIR}/etc/profile.d/10-ywd-env.sh"
install -m 0644 files/ywd-prompt.sh "${ROOTFS_DIR}/etc/profile.d/80-ywd-prompt.sh"
install -m 0644 files/ywd-motd.sh "${ROOTFS_DIR}/etc/profile.d/90-ywd-motd.sh"

install -m 0644 files/issue "${ROOTFS_DIR}/etc/issue"
install -m 0644 files/issue "${ROOTFS_DIR}/etc/issue.net"
install -m 0644 files/motd "${ROOTFS_DIR}/etc/motd"

# Suppress stock dynamic MOTD fragments. YWD's live status is printed from
# /etc/profile.d only for interactive terminals, so scp/sftp and noninteractive
# SSH commands remain clean while PAM may still show our static /etc/motd.
if [ -d "${ROOTFS_DIR}/etc/update-motd.d" ]; then
  find "${ROOTFS_DIR}/etc/update-motd.d" -maxdepth 1 -type f -exec chmod -x {} + || true
fi

printf '%s\n' "$YWD_OS_VERSION" > "${ROOTFS_DIR}/etc/ywd-hotspot/os-version"
printf '%s\n' "$YWD_PI_GEN_COMMIT" > "${ROOTFS_DIR}/etc/ywd-hotspot/pi-gen-commit"

cat > "${ROOTFS_DIR}/etc/ywd-hotspot/os-release" <<EOF
NAME="YWD-Hotspot OS"
PRETTY_NAME="YWD-Hotspot OS M4.1"
VERSION="${YWD_OS_VERSION}"
VERSION_ID="M4.1"
ID=ywd-hotspot
ID_LIKE="raspbian debian"
BASE_OS="Raspberry Pi OS"
BASE_RELEASE="trixie"
TARGET="Raspberry Pi Zero W / Zero WH"
REPOSITORY="https://github.com/merberg-ai/ywd-hotspot"
BRANCH="${YWD_SOURCE_BRANCH}"
COMMIT="${YWD_SOURCE_COMMIT}"
PI_GEN_COMMIT="${YWD_PI_GEN_COMMIT}"
EOF
chmod 0644 "${ROOTFS_DIR}/etc/ywd-hotspot/os-release" \
  "${ROOTFS_DIR}/etc/ywd-hotspot/os-version" \
  "${ROOTFS_DIR}/etc/ywd-hotspot/pi-gen-commit"

cat > "${ROOTFS_DIR}/etc/ywd-hotspot/console-help.txt" <<'EOF'
YWD-Hotspot OS quick commands

  ywd-info              live appliance summary
  ywd-info --all        summary + services + build provenance
  ywd-info --network    Wi-Fi/IP summary
  ywd-services          compact systemd service status
  ywd-build             app/OS/Git/pi-gen build provenance
  ywd-logs              follow all YWD logs
  ywd-logs network      network manager only
  ywd-logs web          dashboard only
  ywd-logs setup        secure first-boot wizard only
  ywd-logs rf           MMDVM-Host + DMRGateway

WebUI:  http://ywd-hotspot.local:8080/
GitHub: https://github.com/merberg-ai/ywd-hotspot
EOF
chmod 0644 "${ROOTFS_DIR}/etc/ywd-hotspot/console-help.txt"

printf 'Installed YWD-Hotspot OS M4.1 identity, MOTD, prompt, and console helpers.\n'
